### PR TITLE
Fixed All Issue

### PR DESCRIPTION
**Pull request by waleedcodes**
Some change in Index.html And app.css

### CODE REVIEW

**Comment by waleedcodes** [comment]
Fix All Issue Check my Pull Request

**Comment by Adedoyin-Emmanuel** [comment]
Screenshot from 2024-02-03 23-31-39

The inputs aren't aligned properly.  Please Fix

**Comment by waleedcodes** [comment]
Now Check the Pull Request

**Comment by Adedoyin-Emmanuel** [comment]
Screenshot from 2024-02-06 04-07-25

The button isn''t aligned with the input elements also on smaller screens, the entire form isn't responsive any longer.

**Comment by waleedcodes** [comment]
### Fix #1
Screenshot_0
Screenshot_11

**Comment by Adedoyin-Emmanuel** [comment]
It works fine now :smile: . Thanks for contributing. By the way, I've other projects you might be interested in contributing to.

**Comment by waleedcodes** [comment]
Done !

**Pull request merged**
